version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    networks:
      - nginx-proxy-manager_default
      - default
    ports:
      - 9090:80
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./mealie/data/:/app/data

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

networks:
  nginx-proxy-manager_default:
    external: true