version: '3'

services:
 
  monitoring:
    image: nicolargo/glances:latest
    restart: unless-stopped
    pid: host
    networks:
     - nginx-proxy-manager_default
     - default
    ports:
     - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"


networks:
  nginx-proxy-manager_default:
    external: true