version: '3.2'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./changedetection-data:/datastore
      - ./proxies.json:/datastore/proxies.json
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      - USE_X_SETTINGS=1
      - HIDE_REFERER=true
      - FETCH_WORKERS=2
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      browser-chrome:
        condition: service_started
    networks:
      - default
      - nginx-proxy-manager_default

  browser-chrome:
    hostname: browser-chrome
    image: seleniarm/standalone-chromium:latest
    networks:
      - default
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true