version: "2"
services:
   adguardhome:
     image: adguard/adguardhome
     container_name: adguardhome
     networks:
      - nginx-proxy-manager_default
     ports:
       - 53:53/tcp
       - 53:53/udp
       - 784:784/udp
       - 853:853/tcp
       - 3001:3000/tcp
       - 83:80/tcp
     volumes:
       - ./work:/opt/adguardhome/work
       - ./conf:/opt/adguardhome/conf

networks:
  nginx-proxy-manager_default:
    external: true